activity_interval_seconds: 60
activity_dir: "./activity"

labels:
  - work
  - hobby
  - uni
  - gaming
  - roochen
  - unknown

hotkeys:
  work: "ctrl+alt+w"
  hobby: "ctrl+alt+h"
  uni: "ctrl+alt+u"
  gaming: "ctrl+alt+g"
  roochen: "ctrl+alt+r"
  clear: "ctrl+alt+0"

merge:
  images_dir: "./images"
  activity_dirs:
    - "./activity"
  output_dir: "./output"
  max_gap_seconds: 120
